# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Boston Routing Blog
tagline: Boston Routing Blog
email: spearsear@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  BostonRouting is an online solver for multi vehicle multi stop optimal routing problem.
  It can be used by various companies who has the need to dispatch its many vehicles to many
  destinations, usually with time box constraints for each stop and capacity constraints
  for each of its vehicles. We have helped landscaping companies, bakeries, trash collection
  companies and home service companies generating their optimal routes on a daily basis.
#baseurl: "/brblog" # the subpath of your site, e.g. /blog
url: "https://blog.bostonrouting.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: /img/favicon.png
permalink: pretty
twitter_username: spearsear
github_username:  spearsear

# Build settings
#theme: minima
#theme: jekyll-bulma
#theme: bulma-clean-theme
remote_theme: chrisrhymes/bulma-clean-theme

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm

# Pagination settings
paginate: 5
paginate_path: "/blog/page:num"

collections:
  products:
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false

footer_menu: footer_menu

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      show_sidebar: true
  -
    scope:
      path: ""
      type: "posts"
    values:
      author: "Spearsear"
      layout: post
      image:
      show_sidebar: true


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

livereload: true

sass:
  style: compressed
  source_dir: _sass

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

markdown: kramdown
highlighter: rouge


